version: 0.1.3

llms:
  openai-gpt3.5:
    type: openai
    params:
      openai_api_key: ""
      model: "gpt-3.5-turbo-0613"
  
  openai-gpt4:
    type: openai
    params:
      openai_api_key: ""
      model: "gpt-4-0613"

  llama-cpp-server:
    type: llama
    params:
      llama_cpp_server_url: "http://localhost:8000"
      api_version: "v1"
      max_tokens: 4096

agents:
  dialogue_agent:
    llm: openai-gpt3.5



